name: Docker Build and Push

on:
  push:
    tags:
      - 'release/v*'  # 匹配以 "release/v" 开头的标签，例如 release/v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build --build-arg API_VERSION=${{ secrets.API_VERSION }} -f hello/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest .

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

      # 推送完成后发送 Webhook
      - name: Send Webhook Notification
        run: |
          curl -X POST ${{ vars.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "tag": "${{ github.ref_name }}",
              "repository": "${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_REPOSITORY }}",
              "status": "success",
              "timestamp": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
            }'
